apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
  labels:
    app.kubernetes.io/name: config
    app.kubernetes.io/part-of: renovate
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: renovate
            image: renovate/renovate:latest
            env:
            - name: RENOVATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: token
            volumeMounts:
            - name: config
              subPath: config.js
              mountPath: /usr/src/app/config.js
          restartPolicy: OnFailure
          volumes:
          - name: config
            configMap:
              name: config