apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: monitoring
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/part-of: monitoring
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/part-of: monitoring
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.5.7
          args:
            - --config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
              protocol: TCP
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/loki.yaml
              subPath: loki.yaml
            - name: loki-data
              mountPath: /loki
      restartPolicy: Always
      volumes:
        - name: loki-config
          configMap:
            items:
              - key: loki-config.yaml
                path: loki.yaml
            name: loki-config
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data
