apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: monitoring
spec:
  ports:
    - name: "http"
      port: 3100
      targetPort: 3100
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: monitoring

