apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: backbone
spec:
  ports:
    - name: "tcp"
      port: 9000
      targetPort: 9000
    - name: "mgmt"
      port: 9001
      targetPort: 9001
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: backbone
