apiVersion: v1
kind: Service
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: monitoring
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: monitoring
