apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: monitoring
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/part-of: monitoring
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir
        app.kubernetes.io/part-of: monitoring
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:2.17.1
          args:
            - -config.file=/etc/mimir/mimir.yaml
            - -target=all
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: mimir-config
              mountPath: /etc/mimir/mimir.yaml
              subPath: mimir.yaml
            - name: mimir-data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: mimir-config
          configMap:
            items:
              - key: mimir.yaml
                path: mimir.yaml
        - name: mimir-data
          persistentVolumeClaim:
            claimName: mimir-data
