apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: backbone
spec:
  ports:
    - name: "amqp"
      port: 5672
      targetPort: 5672
    - name: "mgmt"
      port: 15672
      targetPort: 15672
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: backbone
