apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: monitoring
spec:
  ports:
    - name: "http"
      port: 3200
      targetPort: 3200
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: monitoring
