apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tempo-config
    app.kubernetes.io/part-of: monitoring
data:
  tempo.yaml: |-
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"

    storage:
      trace:
        backend: s3
        s3:
          endpoint: minio.:9000
          bucket: tempo
          access_key: <TODO>
          secret_key: <TODO>
          insecure: true
        wal:
          path: /tmp/tempo/wal

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: default
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: http://mimir.monitoring:8080/api/v1/push
            send_exemplars: true
