apiVersion: v1
kind: Secret
metadata:
  name: app-configuration
  namespace: one-percent-better
  labels:
    app.kubernetes.io/name: app-configuration
    app.kubernetes.io/part-of: one-percent-better
stringData:
  application.yaml: |
    spring:
      datasource:
        url: "<TODO>"
        username: "<TODO>"
        password: "<TODO>"
      rabbitmq:
        host: "<TODO>"
        username: "<TODO>"
        password: "<TODO>"
      ai:
        openai:
          api-key: "<TODO>"
    github:
      username: "<TODO>"
      token: "<TODO>"
    app:
      check-in:
        schedule-cron: "<TODO>"
        bootstrap-projects:
          - "<TODO>"
      reminder:
        schedule-cron: "<TODO>"
