apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: one-percent-better
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      app.kubernetes.io/part-of: one-percent-better
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
        app.kubernetes.io/part-of: one-percent-better
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: app-runtime-options
                  key: options
          image: ghcr.io/shazxrin/one-percent-better:v1.2.0
          name: one-percent-better
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          volumeMounts:
            - name: app-configuration
              subPath: application.yaml
              mountPath: /application/application.yaml
      restartPolicy: Always
      volumes:
        - name: app-configuration
          secret:
            secretName: app-configuration
