apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  labels:
    app.kubernetes.io/name: posgres-init
    app.kubernetes.io/part-of: backbone
data:
  init_db.sql: |-
    CREATE DATABASE "one-percent-better";
    CREATE DATABASE "alif";
