apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: backbone
spec:
  ports:
    - name: "tcp"
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: backbone
