apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: monitoring
spec:
  ports:
    - name: "grpc"
      port: 4317
      targetPort: 4317
    - name: "http"
      port: 4318
      targetPort: 4318
  selector:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: monitoring
