apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: monitoring
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
      app.kubernetes.io/part-of: monitoring
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alloy
        app.kubernetes.io/part-of: monitoring
    spec:
      containers:
        - args:
            - run
            - /etc/alloy/config.alloy
          image: grafana/alloy:v1.10.2
          name: alloy
          ports:
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/alloy
              name: alloy-config
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
      restartPolicy: Always
      volumes:
        - configMap:
            name: alloy-config
          name: alloy-config
